name: Update ACL Lists

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create output folder if not exists
        run: mkdir -p list

      - name: Download URLs from external source
        id: vars
        run: |
          curl -fsSL https://raw.githubusercontent.com/10ium/mihomo_rule/refs/heads/main/urls/urls.txt -o urls.txt
          urls=$(cat urls.txt | xargs)
          echo "urls=$urls" >> $GITHUB_OUTPUT

      - name: Process all list URLs
        id: generate
        run: |
          changed=0

          for url in ${{ steps.vars.outputs.urls }}; do
            filename=$(basename "$url")                          # e.g., Telegram.list
            yaml_file="${filename%.list}.yaml"                   # e.g., Telegram.yaml
            output_path="list/$yaml_file"                        # مسیر خروجی

            echo "Downloading $filename from $url..."
            curl -fsSL "$url" | sed '/^#/d;/^$/d' > "$filename"

            if [ ! -s "$filename" ]; then
              echo "::error::$filename is empty after download and cleanup"
              continue
            fi

            sed 's/^/  - /; s/$/,/' "$filename" > temp_list.txt
            echo "payload:" > "new_$yaml_file"
            cat temp_list.txt >> "new_$yaml_file"
            rm temp_list.txt "$filename"

            if [ -f "$output_path" ] && diff -q "$output_path" "new_$yaml_file" >/dev/null; then
              echo "No changes in $yaml_file"
              rm "new_$yaml_file"
            else
              echo "Changes detected in $yaml_file"
              mv "new_$yaml_file" "$output_path"
              changed=1
            fi
          done

          if [ "$changed" -eq 1 ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit & Push changes
        if: steps.generate.outputs.changed == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add list/*.yaml
          git commit -m "chore: Update ACL YAML files ($(date -u +'%Y-%m-%d'))"
          git push
