name: Update ACL Lists

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch .list files from ACL4SSR/Clash
        id: fetch
        run: |
          curl -s https://api.github.com/repos/ACL4SSR/ACL4SSR/contents/Clash \
            | jq -r '.[] | select(.name | endswith(".list")) | .name' > file_list.txt

          if [ ! -s file_list.txt ]; then
            echo "::error::No .list files found in ACL4SSR/Clash"
            exit 1
          fi

      - name: Process and convert to YAML
        id: convert
        run: |
          changed=0

          while read -r filename; do
            url="https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/$filename"
            yaml_file="${filename%.list}.yaml"

            echo "Processing $filename..."

            curl -fsSL "$url" | sed '/^#/d;/^$/d' > "$filename"

            if [ ! -s "$filename" ]; then
              echo "::warning::$filename is empty after processing"
              continue
            fi

            sed 's/^/  - /; s/$/,/' "$filename" > temp_list.txt
            echo "payload:" > "new_$yaml_file"
            cat temp_list.txt >> "new_$yaml_file"
            rm temp_list.txt

            if [ -f "$yaml_file" ] && diff -q "$yaml_file" "new_$yaml_file" >/dev/null; then
              echo "No changes in $yaml_file"
              rm "new_$yaml_file"
            else
              echo "Updating $yaml_file"
              mv "new_$yaml_file" "$yaml_file"
              changed=1
            fi
          done < file_list.txt

          if [ "$changed" -eq 1 ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit & Push changes
        if: steps.convert.outputs.changed == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add *.yaml
          git commit -m "chore: Update ACL YAML files ($(date -u +'%Y-%m-%d'))"
          git push
