name: Update BanProgramAD YAML

on:
  schedule:
    # هر روز ساعت 00:00 به وقت UTC
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download & preprocess BanProgramAD.list
        run: |
          # دانلود و حذف کامنت‌ها/خطوط خالی
          curl -fsSL https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list \
            | sed '/^#/d;/^$/d' > BanProgramAD.list

          if [ ! -s BanProgramAD.list ]; then
            echo "::error::BanProgramAD.list is empty after preprocessing"
            exit 1
          fi

      - name: Generate BanProgramAD.yaml
        id: generate
        run: |
          # تبدیل هر خط به فرمت YAML با پیش‌وند و پس‌وند کاما
          sed 's/^/  - /; s/$/,/' BanProgramAD.list > temp_list.txt

          # ساخت فایل جدید
          echo "payload:" > new_BanProgramAD.yaml
          cat temp_list.txt >> new_BanProgramAD.yaml

          # اگر قبلاً فایل وجود داشت و بدون تغییر است:
          if [ -f BanProgramAD.yaml ] && diff -q BanProgramAD.yaml new_BanProgramAD.yaml >/dev/null; then
            echo "changed=false" >> $GITHUB_OUTPUT
            echo "No changes detected"
            exit 0
          fi

          # در صورت تغییر، جایگزینی فایل و علامت‌گذاری تغییر
          mv new_BanProgramAD.yaml BanProgramAD.yaml
          rm temp_list.txt
          echo "changed=true" >> $GITHUB_OUTPUT

      - name: Commit & Push changes
        if: steps.generate.outputs.changed == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add BanProgramAD.yaml
          git commit -m "chore: Update BanProgramAD.yaml ($(date -u +'%Y-%m-%d'))"
          git push
