# .github/workflows/update-ponzi-list.yml
name: Update Ponzi Scam Sites List

on:
  schedule:
    - cron: '0 2 * * *'       # run at 02:00 UTC daily
  workflow_dispatch:         # allow manual runs

jobs:
  fetch-ponzi-list:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download all Ponzi HTML pages with browser UA
        run: |
          USER_AGENT="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.0.0 Safari/537.36"
          mkdir pages
          curl -fsSL -A "$USER_AGENT" "https://www.webamooz.com/ponzi/" -o pages/page1.html
          max_page=$(grep -oP 'href="https://www.webamooz.com/ponzi/page/\K[0-9]+' pages/page1.html | sort -n | tail -1)
          [ -z "$max_page" ] && max_page=1
          for i in $(seq 2 $max_page); do
            curl -fsSL -A "$USER_AGENT" "https://www.webamooz.com/ponzi/page/$i/" -o "pages/page$i.html"
          done

      - name: Extract domains from all pages
        run: |
          shopt -s nullglob
          > all_domains.txt
          for f in pages/page*.html; do
            sed -n '/<tbody>/,/<\/tbody>/p' "$f" \
              | sed 's/\[\.\]/./g' \
              | grep -oP '(?<=<td>)[A-Za-z0-9.-]+\.[A-Za-z]{2,6}(?=</td>)' || true \
              >> all_domains.txt
          done
          sort -u all_domains.txt > temp_domains.txt
          rm -rf pages all_domains.txt

      - name: Build YAML payload
        run: |
          echo "payload:" > new_ponzi-sites.yaml
          if [ -s temp_domains.txt ]; then
            sed 's/^/  - DOMAIN-SUFFIX,/; s/$/,/' temp_domains.txt \
              >> new_ponzi-sites.yaml
          fi
          rm temp_domains.txt

      - name: Compare & update YAML
        id: compare
        run: |
          target="ponzi-sites.yaml"
          if [ ! -f "$target" ] || ! diff -q "$target" new_ponzi-sites.yaml >/dev/null; then
            mv new_ponzi-sites.yaml "$target"
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            rm new_ponzi-sites.yaml
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: "Commit & Push if changed"
        if: steps.compare.outputs.changed == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add ponzi-sites.yaml
          git commit -m "chore: Update Ponzi sites list ($(date -u +'%Y-%m-%d'))"
          git push
