name: Update Ponzi Scam Sites List

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  fetch-ponzi-list:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download all Ponzi HTML pages
        run: |
          mkdir pages
          echo "Fetching page 1..."
          curl -fsSL "https://www.webamooz.com/ponzi/" -o pages/page1.html

          # پیدا کردن تعداد صفحات از pagination
          max_page=$(grep -oP 'href="https://www.webamooz.com/ponzi/page/\K[0-9]+' pages/page1.html | sort -n | tail -1)
          if [ -z "$max_page" ]; then max_page=1; fi
          echo "Found $max_page pages."

          for i in $(seq 2 $max_page); do
            echo "Fetching page $i..."
            curl -fsSL "https://www.webamooz.com/ponzi/page/$i/" -o "pages/page$i.html"
          done

      - name: Extract domains from all pages
        run: |
          shopt -s nullglob
          > all_domains.txt
          for f in pages/page*.html; do
            domains=$(sed -n '/<tbody>/,/<\/tbody>/p' "$f" \
              | sed 's/\[\.\]/./g' \
              | grep -oP '(?<=<td>)[A-Za-z0-9.-]+\.[A-Za-z]{2,6}(?=</td>)' || true)
            [ -n "$domains" ] && echo "$domains" >> all_domains.txt
          done
          sort -u all_domains.txt > temp_domains.txt
          rm -rf pages all_domains.txt

      - name: Build YAML payload
        run: |
          # همیشه یک فایل new_ponzi-sites.yaml می‌سازیم، حتی اگر خالی باشه
          echo "payload:" > new_ponzi-sites.yaml
          if [ -s temp_domains.txt ]; then
            sed 's/^/  - DOMAIN-SUFFIX,/; s/$/,/' temp_domains.txt >> new_ponzi-sites.yaml
          else
            echo "::notice::No domains extracted, skipping update." 
          fi
          rm temp_domains.txt

      - name: Compare and update YAML
        id: compare
        run: |
          target="ponzi-sites.yaml"

          # اگر فقط header بود (هیچ دامنه‌ای نیومده)، new_ponzi-sites.yaml رو حذف و بدون تغییر خروجی بده
          if [ "$(wc -l < new_ponzi-sites.yaml)" -le 1 ]; then
            echo "changed=false" >> $GITHUB_OUTPUT
            rm new_ponzi-sites.yaml
          # اگر فایل قبلی وجود داره و هیچ تغییری نداشته، صرفاً حذف فایل جدید
          elif [ -f "$target" ] && diff -q "$target" new_ponzi-sites.yaml >/dev/null; then
            echo "changed=false" >> $GITHUB_OUTPUT
            rm new_ponzi-sites.yaml
          else
            mv new_ponzi-sites.yaml "$target"
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit & Push if changed
        if: steps.compare.outputs.changed == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add ponzi-sites.yaml
          git commit -m "chore: Update Ponzi sites list ($(date -u +'%Y-%m-%d'))"
          git push
