name: Process Webamooz Warning List

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  process_domains:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Download and process domain list
        run: |
          import requests
          import re

          url = "https://raw.githubusercontent.com/Webamoozcom/warning-list/master/index.html"
          response = requests.get(url)
          content = response.text

          # پیدا کردن تمام URLها با regex
          urls = re.findall(r'"url"\s*:\s*"([^"]+)"', content)

          domains = set()
          for u in urls:
              u = u.strip()
              clean_url = re.sub(r'^(https?://)?(www\.)?', '', u, flags=re.IGNORECASE)

              if "t.me/" in clean_url:
                  domain = clean_url.split('/')[0].lower()
                  path = '/'.join(clean_url.split('/')[1:])
                  final_domain = f"{domain}/{path}" if path else domain
              else:
                  final_domain = clean_url.split('/')[0].split('?')[0].split('#')[0].lower()

              if '.' in final_domain or "t.me" in final_domain:
                  domains.add(final_domain)

          with open("warning-list.yaml", "w", encoding='utf-8') as f:
              f.write("payload:\n")
              for domain in sorted(domains):
                  f.write(f"  - DOMAIN-SUFFIX,{domain},\n")

        shell: python

      - name: Commit and push changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add warning-list.yaml
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update warning list domains" && git push)
